<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearch($query)
    {
        $qb = $this->createQueryBuilder('users')
            ->select('users.username');
        $qb->where('users.username LIKE :user')
            ->setParameter('user', '%'.$query.'%');

        return $qb
            ->getQuery()
            ->getArrayResult();
    }
}
