<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllTasks($id)
    {
        $qb = $this->createQueryBuilder('category')->select('category.id')
            ->innerJoin('category.tasks', 'tasks')->addSelect('tasks.name', 'tasks.id');

        $qb->where('category.id = :id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult();
    }
}
