<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findById($id)
    {
        $qb = $this->createQueryBuilder('project')
            ->select('project.id', 'project.name', 'project.createdAt');

        $qb->where('project.id = :id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult();
    }


    public function findByUser($user)
    {
        $qb = $this->createQueryBuilder('project')
            ->select('project.id', 'project.name', 'project.createdAt')
            ->innerJoin('project.users', 'users');

        $qb->where('users = :user')
            ->setParameter('user', $user);

        return $qb
            ->getQuery()
            ->getResult();
    }


    public function findAllUsers($id)
    {
        $qb = $this->createQueryBuilder('project')->select('project.id')
            ->innerJoin('project.users', 'users')->addSelect('users.username');

        $qb->where('project.id = :id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function findAllCategories($id)
    {
        $qb = $this->createQueryBuilder('project')->select('project.id')
            ->innerJoin('project.categories', 'categories')->addSelect('categories.name', 'categories.id');

        $qb->where('project.id = :id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult();
    }

}
